### ISSUE TITLE
No connected devices found. Returning best error VRInitError_Init_HmdNotFound

### ISSUE THREAD

**Issue by thezenmaster** [ValveSoftware/virtual_display#2]
The vrserver log reports that the driver inits correctly. However, Steam VR reports that no headset is present:

virtual_display: Headset connected to Intel(R) HD Graphics 530.
virtual_display: Using NVIDIA GeForce GTX 1070 as primary graphics adapter.
virtual_display: Launching "E:\SteamVR Virtual Display\bin\win32\virtual_display.exe" 1920 0 2160 1200 90 1
virtual_display: Adding Virtual device
...........................................
No connected devices found. Returning best error VRInitError_Init_HmdNotFound
I am able to work around the issue by also adding an HMD device on Init, TrackedDeviceClass_HMD.

Am I missing something or TrackedDeviceClass_DisplayRedirect cannot be used on it own?

**Comment by aleiby** [comment]
It is not intended to be used on its own.  Instead, it is intended to be used in conjunction with a "proper" driver (which provides tracking, etc.) like driver_lighthouse.  Those drivers must also be DisplayRedirect aware - such that they don't fail if they do not find the hmd display directly attached if a DisplayRedirect driver has been activated.  This, for instance, prevents this being used with driver_oculus.

**Comment by thezenmaster** [comment]
The Oculus part is kind of a bummer. Thanks for your reply!
